CREATE TABLE app_users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    CONSTRAINT uk_app_users_email UNIQUE (email)
);

CREATE TABLE email_outbox
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload TEXT NOT NULL
);
