CREATE TABLE tasks
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(255) NOT NULL,
    description  TEXT,
    owner_id     BIGINT NOT NULL,
    status       VARCHAR(20) NOT NULL DEFAULT 'TODO',
    completed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_tasks_owner FOREIGN KEY (owner_id) REFERENCES app_users (id),
    CONSTRAINT ck_tasks_status CHECK (status IN ('TODO', 'COMPLETED')),
    CONSTRAINT ck_tasks_completion CHECK (
        (status = 'TODO' AND completed_at IS NULL)
        OR (status = 'COMPLETED' AND completed_at IS NOT NULL)
    )
);

CREATE INDEX idx_tasks_owner_id ON tasks (owner_id);
